### ISSUE TITLE
无法抓取

### ISSUE THREAD

**Issue by jie-wu1** [DisasterMeng/Gui-Amazon-Review#2]
![企业微信截图_155910246222](https://user-images.githubusercontent.com/50826374/58528535-72920700-8209-11e9-8905-265faacd6f9a.png)

很多ASIN，0.6版本可以抓取，0.8版本反而不能抓了

**Comment by LingHanChuJian** [comment]
@jie-wu1  这个B07ML35KHK 经过我的测试都可以啊
![test](https://user-images.githubusercontent.com/22723360/58528895-221ba900-820b-11e9-9325-ca08f36440c4.png)
上面有格式条的是 0.8 版
下面为 0.6版

**Comment by LingHanChuJian** [comment]
@jie-wu1  该 asin 的评论总数 是 7 条 
[https://www.amazon.com/YOUNGDO-Digital-Bathroom-Accurate-Backlight/product-reviews/B07ML35KHK/ref=cm_cr_dp_d_show_all_top?ie=UTF8&reviewerType=all_reviews](url)

**Comment by jie-wu1** [comment]
美国站没有问题，德国站和意大利站试了好几个ASIN ，不是卡在机器人验证就是卡在解析数据

**Comment by LingHanChuJian** [comment]
@jie-wu1  德国站和意大利站使用asin 方便给出么?

**Comment by sujianqingfeng** [comment]
@jie-wu1 
你们QQ聊呀，这样交流多费劲。
他的QQ2739069093，我的QQ121116111
