### ISSUE TITLE
总是会出现机器人验证了

### ISSUE THREAD

**Issue by Vinking-Yang** [DisasterMeng/Gui-Amazon-Review#4]

**Comment by LingHanChuJian** [comment]
@Vinking-Yang  这个问题也比较麻烦 我这边做了 代理处理的  但是代理方面可能不太行把  说白了就是 ip 不太 优质把 。 你可以找下优质的代理 自己实现下

**Comment by LingHanChuJian** [comment]
@Vinking-Yang  对于这个情况我新添加了页码 ， 你可以从上次遇到机器人验证的页码， 重新开始爬取

**Comment by LingHanChuJian** [comment]
@Vinking-Yang  对于这个情况我新添加了页码 ， 你可以从上次遇到机器人验证的页码， 重新开始爬取

**Comment by Vinking-Yang** [comment]
好的谢谢
